# Count Encoders 

Note: Not present in Scikit Learn, Hence I need to use Category Encoders Class.

In [18]:
import pandas as pd
import numpy as np
import sklearn
import category_encoders as ce
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder

In [19]:
# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

df = pd.DataFrame(data)

df.head()

    Age       State    Education    Package
0  54.0  Tamil Nadu  High School  40.612049
1  49.0       Delhi           PG  56.921076
2   NaN   Telangana  High School  34.360550
3  54.0       Delhi           PG  78.887278
4  33.0       Delhi           PG  41.137241

In [20]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Package']), df['Package'], test_size=0.2, random_state=42)

In [21]:
X_train['State'].value_counts()

State
Delhi          18
Tamil Nadu     17
Telangana      17
Maharashtra    14
Karnataka      14
Name: count, dtype: int64

In [22]:
df.isnull().sum()

Age          5
State        0
Education    0
Package      0
dtype: int64

In [23]:
preprocessor = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', ce.CountEncoder(), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])
sklearn.set_config(transform_output="pandas")

In [24]:
preprocessor.fit_transform(X_train)

    age_missing__Age  cat_state__State  education_ordinal__Education
55         38.666667                17                           0.0
88         42.000000                14                           1.0
26         38.666667                14                           1.0
42         39.000000                18                           1.0
69         33.000000                18                           0.0
..               ...               ...                           ...
60         45.000000                17                           0.0
71         44.000000                17                           0.0
14         50.000000                14                           2.0
92         31.000000                14                           2.0
51         23.000000                17                           0.0

[80 rows x 3 columns]

# Handling Various Paramters in Count Encoder

In [34]:
# parameters
import pandas as pd
import numpy as np
import category_encoders as ce

# Simulating a dataset with real missing values
np.random.seed(42)
parameter_df = pd.DataFrame({
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100)
})

state_missing = np.random.rand(len(parameter_df)) < 0.1
education_missing = np.random.rand(len(parameter_df)) < 0.1

parameter_df.loc[state_missing, 'State'] = np.nan
parameter_df.loc[education_missing, 'Education'] = np.nan

parameter_df.head(25)

          State    Education
0         Delhi           PG
1     Telangana  High School
2           NaN           UG
3     Telangana  High School
4     Telangana           PG
5    Tamil Nadu           PG
6   Maharashtra           UG
7   Maharashtra  High School
8   Maharashtra           PG
9     Telangana           UG
10        Delhi           PG
11  Maharashtra           PG
12    Telangana  High School
13   Tamil Nadu          NaN
14        Delhi  High School
15   Tamil Nadu           PG
16        Delhi           UG
17    Telangana           PG
18          NaN  High School
19        Delhi  High School
20   Tamil Nadu           UG
21    Telangana           PG
22          NaN           PG
23    Karnataka           UG
24    Karnataka           PG

In [35]:
parameter_df.isna().sum()

State        11
Education    13
dtype: int64

In [38]:
# Initialize the CountEncoder with various parameters
encoder = ce.CountEncoder(
    cols=['State', 'Education'],  # Specify columns to encode. None would automatically select categorical columns.
    handle_missing='error',  # This should throw error
    handle_unknown='error',  # Throw an error
)

In [37]:
# Fit and transform the dataset
encoded_df = encoder.fit_transform(parameter_df)

print(encoded_df.head(25))

ValueError: Columns to be encoded cannot contain null

In [41]:
# Initialize the CountEncoder with various parameters
encoder_handle_missing  = ce.CountEncoder(
    cols=['State', 'Education'],  # Specify columns to encode. None would automatically select categorical columns.
    handle_missing='value',  # This should throw error
    handle_unknown='error',  # Throw an error
)

In [42]:
# Fit and transform the dataset
encoded_df = encoder_handle_missing.fit_transform(parameter_df)

print(encoded_df.head(25))

    State  Education
0      25         36
1      18         28
2      11         23
3      18         28
4      18         36
5      18         36
6      14         23
7      14         28
8      14         36
9      18         23
10     25         36
11     14         36
12     18         28
13     18         13
14     25         28
15     18         36
16     25         23
17     18         36
18     11         28
19     25         28
20     18         23
21     18         36
22     11         36
23     14         23
24     14         36

In [43]:
encoder_handle_missing.mapping

{'State': State
 Delhi          25
 Telangana      18
 Tamil Nadu     18
 Maharashtra    14
 Karnataka      14
 NaN            11
 Name: count, dtype: int64,
 'Education': Education
 PG             36
 High School    28
 UG             23
 NaN            13
 Name: count, dtype: int64}

# Frequency Encoders

In [44]:
# Simulating a dataset
data = {
    'Age': np.random.randint(20, 60, size=100).astype(float),  # Random ages between 20 and 60
    'State': np.random.choice(['Karnataka', 'Tamil Nadu', 'Maharashtra', 'Delhi', 'Telangana'], size=100),
    'Education': np.random.choice(['High School', 'UG', 'PG'], size=100),
    'Package': np.random.rand(100) * 100  # Random package values for demonstration
}

# Introducing missing values in 'Age' column (5%)
np.random.seed(0)  # For reproducibility
missing_indices = np.random.choice(data['Age'].shape[0], replace=False, size=int(data['Age'].shape[0] * 0.05))
data['Age'][missing_indices] = np.nan

freqdf = pd.DataFrame(data)

freqdf.head()

    Age        State    Education    Package
0  24.0   Tamil Nadu           PG  75.513726
1  55.0    Telangana           UG  62.030955
2   NaN  Maharashtra           PG  70.407977
3  50.0    Telangana  High School  21.296416
4  29.0  Maharashtra  High School  13.637148

In [46]:
X_train, X_test, y_train, y_test = train_test_split(freqdf.drop(columns=['Package']), df['Package'], test_size=0.2, random_state=42)

In [47]:
preprocessor_freq = ColumnTransformer(
    transformers=[
        ('age_missing', SimpleImputer(strategy='mean'), ['Age']),
        ('cat_state', ce.CountEncoder(normalize = True), ['State']),
        ('education_ordinal', OrdinalEncoder(), ['Education'])
    ])
sklearn.set_config(transform_output="pandas")

In [48]:
preprocessor_freq.fit_transform(X_train)

    age_missing__Age  cat_state__State  education_ordinal__Education
55             42.76            0.2000                           0.0
88             38.00            0.2375                           2.0
26             42.76            0.2000                           1.0
42             29.00            0.2375                           0.0
69             42.00            0.2500                           0.0
..               ...               ...                           ...
60             37.00            0.2375                           0.0
71             54.00            0.2500                           0.0
14             47.00            0.2375                           2.0
92             31.00            0.1750                           2.0
51             40.00            0.2000                           2.0

[80 rows x 3 columns]